import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./src/i18n/request.ts');

const isDev = process.env.NODE_ENV !== 'production';
// Backend origin (API + presigned upload target) for CSP connect-src.
// `||` (not `??`): an empty build-arg arrives as '' and must also fall back.
const backendOrigin = new URL(process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:3000/api')
  .origin;
/**
 * NEXT_PUBLIC_MEDIA_HOSTS entries: bare hostname (`media.example.com` → https)
 * or a full origin (`http://157.90.1.2:8081` — the no-domain deploy mode).
 */
const mediaEntries = (process.env.NEXT_PUBLIC_MEDIA_HOSTS?.split(',') ?? [])
  .map((entry) => entry.trim())
  .filter(Boolean)
  .map((entry) => new URL(entry.includes('://') ? entry : `https://${entry}`));
// Dev media/storage lives on MinIO; prod comes from NEXT_PUBLIC_MEDIA_HOSTS.
const mediaOrigins = [
  ...(isDev ? ['http://localhost:9000'] : []),
  ...mediaEntries.map((u) => u.origin),
];

/**
 * Pragmatic CSP: source allowlists + frame/object hardening. `unsafe-inline`
 * for scripts stays because Next injects inline bootstrap scripts and the
 * theme script runs before hydration; a nonce-based policy needs middleware
 * and is the follow-up step. `unsafe-eval` is dev-only (webpack HMR).
 */
const csp = [
  `default-src 'self'`,
  `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ''}`,
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data: blob: ${mediaOrigins.join(' ')}`.trim(),
  // XHR: API calls + direct presigned PUT uploads to object storage.
  `connect-src 'self' ${backendOrigin} ${mediaOrigins.join(' ')}`.trim(),
  `font-src 'self' data:`,
  `object-src 'none'`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `frame-ancestors 'none'`,
].join('; ');

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // Self-contained server bundle for the Docker image (node server.js).
  output: 'standalone',
  // Pin the tracing root to this app: with sibling lockfiles (backend repo
  // root, $HOME) Next guesses wrong and nests server.js deep inside
  // .next/standalone/<full/path>. Pinned, it is always at the top level.
  outputFileTracingRoot: import.meta.dirname,
  experimental: {
    optimizePackageImports: ['framer-motion', '@studio-freight/lenis'],
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      {
        protocol: 'http',
        hostname: 'localhost',
      },
      // Allow MinIO in dev + production S3/CDN — from NEXT_PUBLIC_MEDIA_HOSTS
      // (bare hostnames or full origins, see mediaEntries above).
      ...mediaEntries.map((u) => ({
        protocol: u.protocol.replace(':', ''),
        hostname: u.hostname,
        ...(u.port ? { port: u.port } : {}),
      })),
    ],
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Content-Security-Policy', value: csp },
        ],
      },
    ];
  },
  async rewrites() {
    // robots.txt / sitemap.xml are generated by the backend (single source of
    // truth, DB-driven sitemap) but crawlers only look at the site root —
    // proxy them through the storefront domain.
    const backend = process.env.BACKEND_INTERNAL_URL ?? 'http://localhost:3000/api';
    return [
      { source: '/robots.txt', destination: `${backend}/robots.txt` },
      { source: '/sitemap.xml', destination: `${backend}/sitemap.xml` },
    ];
  },
};

export default withNextIntl(nextConfig);
