import createNextIntlPlugin from 'next-intl/plugin';

const withNextIntl = createNextIntlPlugin('./src/i18n/request.ts');

const isDev = process.env.NODE_ENV !== 'production';
// Backend origin (API + presigned upload target) for CSP connect-src.
const backendOrigin = new URL(process.env.NEXT_PUBLIC_BACKEND_URL ?? 'http://localhost:3000/api')
  .origin;
const mediaHosts = (process.env.NEXT_PUBLIC_MEDIA_HOSTS?.split(',').filter(Boolean) ?? []).map(
  (host) => `https://${host.trim()}`,
);
// Dev media/storage lives on MinIO; prod comes from NEXT_PUBLIC_MEDIA_HOSTS.
const mediaOrigins = [...(isDev ? ['http://localhost:9000'] : []), ...mediaHosts];

/**
 * Pragmatic CSP: source allowlists + frame/object hardening. `unsafe-inline`
 * for scripts stays because Next injects inline bootstrap scripts and the
 * theme script runs before hydration; a nonce-based policy needs middleware
 * and is the follow-up step. `unsafe-eval` is dev-only (webpack HMR).
 */
const csp = [
  `default-src 'self'`,
  `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ''}`,
  `style-src 'self' 'unsafe-inline'`,
  `img-src 'self' data: blob: ${mediaOrigins.join(' ')}`.trim(),
  // XHR: API calls + direct presigned PUT uploads to object storage.
  `connect-src 'self' ${backendOrigin} ${mediaOrigins.join(' ')}`.trim(),
  `font-src 'self' data:`,
  `object-src 'none'`,
  `base-uri 'self'`,
  `form-action 'self'`,
  `frame-ancestors 'none'`,
].join('; ');

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  // Self-contained server bundle for the Docker image (node server.js).
  output: 'standalone',
  // Pin the tracing root to this app: with sibling lockfiles (backend repo
  // root, $HOME) Next guesses wrong and nests server.js deep inside
  // .next/standalone/<full/path>. Pinned, it is always at the top level.
  outputFileTracingRoot: import.meta.dirname,
  experimental: {
    optimizePackageImports: ['framer-motion', '@studio-freight/lenis'],
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    remotePatterns: [
      {
        protocol: 'http',
        hostname: 'localhost',
      },
      // Allow MinIO in dev + production S3/CDN — set NEXT_PUBLIC_MEDIA_HOSTS
      // to a comma-separated list of additional hostnames.
      ...(process.env.NEXT_PUBLIC_MEDIA_HOSTS?.split(',').filter(Boolean) ?? []).map(
        (host) => ({ protocol: 'https', hostname: host }),
      ),
    ],
  },
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-Frame-Options', value: 'DENY' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Content-Security-Policy', value: csp },
        ],
      },
    ];
  },
  async rewrites() {
    // robots.txt / sitemap.xml are generated by the backend (single source of
    // truth, DB-driven sitemap) but crawlers only look at the site root —
    // proxy them through the storefront domain.
    const backend = process.env.BACKEND_INTERNAL_URL ?? 'http://localhost:3000/api';
    return [
      { source: '/robots.txt', destination: `${backend}/robots.txt` },
      { source: '/sitemap.xml', destination: `${backend}/sitemap.xml` },
    ];
  },
};

export default withNextIntl(nextConfig);
