/**
 * Fixture data for the demo showcase: 25 published cars across the seeded
 * catalog. Slugs are stable so the seed is idempotent (re-runs skip cars that
 * already exist and have photos).
 */

export interface DemoCarSpec {
  readonly slug: string;
  readonly makeSlug: string;
  readonly modelSlug: string;
  readonly year: number;
  readonly title: string;
  readonly description: string;
  readonly priceUsd: number;
  readonly mileageKm: number;
  readonly bodyTypeSlug: string;
  readonly fuelTypeSlug: string;
  readonly transmissionSlug: string;
  readonly driveTypeSlug: string;
  readonly colorSlug: string;
  readonly engineVolumeL: string;
  readonly powerHp: number;
  readonly city: string;
  readonly optionSlugs: readonly string[];
}

/**
 * Wikipedia pages used as photo sources per catalog model. The first page
 * that yields usable images wins; later entries are fallbacks.
 */
export const WIKI_PAGES_BY_MODEL: Record<string, readonly string[]> = {
  '3-series': ['BMW 3 Series (G20)', 'BMW 3 Series'],
  '5-series': ['BMW 5 Series (G30)', 'BMW 5 Series'],
  x5: ['BMW X5 (G05)', 'BMW X5'],
  a4: ['Audi A4 (B9)', 'Audi A4'],
  a6: ['Audi A6 (C8)', 'Audi A6'],
  q5: ['Audi Q5'],
  'c-class': ['Mercedes-Benz C-Class (W205)', 'Mercedes-Benz C-Class'],
  'e-class': ['Mercedes-Benz E-Class (W213)', 'Mercedes-Benz E-Class'],
  glc: ['Mercedes-Benz GLC (X253)', 'Mercedes-Benz GLC'],
  passat: ['Volkswagen Passat (B8)', 'Volkswagen Passat'],
  tiguan: ['Volkswagen Tiguan'],
  camry: ['Toyota Camry (XV70)', 'Toyota Camry'],
  rav4: ['Toyota RAV4 (XA50)', 'Toyota RAV4'],
  'model-3': ['Tesla Model 3'],
  'model-y': ['Tesla Model Y'],
};

export const DEMO_CARS: readonly DemoCarSpec[] = [
  {
    // Matches the listing created by the base seed so it gains photos too.
    slug: 'bmw-5-series-2021-demo',
    makeSlug: 'bmw',
    modelSlug: '5-series',
    year: 2021,
    title: 'BMW 5 Series 530i xDrive 2021',
    description: 'Один власник, повна історія обслуговування, без ДТП.',
    priceUsd: 38500,
    mileageKm: 42000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'black',
    engineVolumeL: '2.0',
    powerHp: 248,
    city: 'Київ',
    optionSlugs: ['leather', 'cruise', 'heated-seats', 'led-headlights'],
  },
  {
    slug: 'bmw-5-series-2019-demo-02',
    makeSlug: 'bmw',
    modelSlug: '5-series',
    year: 2019,
    title: 'BMW 520d Steptronic 2019',
    description: 'Економічний дизель, сервісна книжка, свіжа гума. Стан дуже добрий.',
    priceUsd: 29900,
    mileageKm: 98000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'diesel',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'rwd',
    colorSlug: 'white',
    engineVolumeL: '2.0',
    powerHp: 190,
    city: 'Одеса',
    optionSlugs: ['climate', 'cruise', 'parking-sensors'],
  },
  {
    slug: 'bmw-3-series-2020-demo-03',
    makeSlug: 'bmw',
    modelSlug: '3-series',
    year: 2020,
    title: 'BMW 320i Sport Line 2020',
    description: 'Пригнаний з Німеччини, розмитнений, перший власник в Україні.',
    priceUsd: 27500,
    mileageKm: 61000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'rwd',
    colorSlug: 'blue',
    engineVolumeL: '2.0',
    powerHp: 184,
    city: 'Київ',
    optionSlugs: ['apple-carplay', 'cruise', 'led-headlights'],
  },
  {
    slug: 'bmw-3-series-2022-demo-04',
    makeSlug: 'bmw',
    modelSlug: '3-series',
    year: 2022,
    title: 'BMW 330e xDrive M Sport 2022',
    description: 'Плагін-гібрид, залишок заводської гарантії, максимальна комплектація.',
    priceUsd: 36900,
    mileageKm: 33000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'hybrid',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'grey',
    engineVolumeL: '2.0',
    powerHp: 292,
    city: 'Львів',
    optionSlugs: ['leather', 'camera-360', 'heated-seats', 'apple-carplay', 'led-headlights'],
  },
  {
    slug: 'bmw-x5-2020-demo-05',
    makeSlug: 'bmw',
    modelSlug: 'x5',
    year: 2020,
    title: 'BMW X5 xDrive30d 2020',
    description: 'Офіційний, обслуговувався у дилера, без фарбованих елементів.',
    priceUsd: 52000,
    mileageKm: 74000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'diesel',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'black',
    engineVolumeL: '3.0',
    powerHp: 265,
    city: 'Київ',
    optionSlugs: ['leather', 'panoramic-roof', 'camera-360', 'heated-seats'],
  },
  {
    slug: 'bmw-x5-2021-demo-06',
    makeSlug: 'bmw',
    modelSlug: 'x5',
    year: 2021,
    title: 'BMW X5 xDrive40i 2021',
    description: 'Бензиновий рядний шестициліндровий, ідеальний стан, повний привід.',
    priceUsd: 58900,
    mileageKm: 45000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'white',
    engineVolumeL: '3.0',
    powerHp: 340,
    city: 'Дніпро',
    optionSlugs: ['leather', 'panoramic-roof', 'camera-360', 'apple-carplay'],
  },
  {
    slug: 'audi-a4-2019-demo-07',
    makeSlug: 'audi',
    modelSlug: 'a4',
    year: 2019,
    title: 'Audi A4 40 TFSI S tronic 2019',
    description: 'Доглянутий седан бізнес-класу, два комплекти коліс у подарунок.',
    priceUsd: 24500,
    mileageKm: 88000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'robot',
    driveTypeSlug: 'fwd',
    colorSlug: 'silver',
    engineVolumeL: '2.0',
    powerHp: 190,
    city: 'Харків',
    optionSlugs: ['climate', 'cruise', 'parking-sensors'],
  },
  {
    slug: 'audi-a4-2021-demo-08',
    makeSlug: 'audi',
    modelSlug: 'a4',
    year: 2021,
    title: 'Audi A4 45 TFSI quattro 2021',
    description: 'Рестайлінг, матричні фари, віртуальна панель приладів.',
    priceUsd: 31900,
    mileageKm: 39000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'robot',
    driveTypeSlug: 'awd',
    colorSlug: 'black',
    engineVolumeL: '2.0',
    powerHp: 245,
    city: 'Київ',
    optionSlugs: ['leather', 'led-headlights', 'apple-carplay', 'heated-seats'],
  },
  {
    slug: 'audi-a6-2019-demo-09',
    makeSlug: 'audi',
    modelSlug: 'a6',
    year: 2019,
    title: 'Audi A6 50 TDI quattro 2019',
    description: 'Потужний та економічний дизель V6, пневмопідвіска, стан нового авто.',
    priceUsd: 32500,
    mileageKm: 92000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'diesel',
    transmissionSlug: 'robot',
    driveTypeSlug: 'awd',
    colorSlug: 'grey',
    engineVolumeL: '3.0',
    powerHp: 286,
    city: 'Львів',
    optionSlugs: ['leather', 'camera-360', 'panoramic-roof'],
  },
  {
    slug: 'audi-a6-2021-demo-10',
    makeSlug: 'audi',
    modelSlug: 'a6',
    year: 2021,
    title: 'Audi A6 45 TFSI quattro 2021',
    description: 'Один власник, купувався новим в Україні, повна історія.',
    priceUsd: 39900,
    mileageKm: 48000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'robot',
    driveTypeSlug: 'awd',
    colorSlug: 'blue',
    engineVolumeL: '2.0',
    powerHp: 245,
    city: 'Київ',
    optionSlugs: ['leather', 'cruise', 'heated-seats', 'android-auto'],
  },
  {
    slug: 'audi-q5-2020-demo-11',
    makeSlug: 'audi',
    modelSlug: 'q5',
    year: 2020,
    title: 'Audi Q5 45 TFSI quattro 2020',
    description: 'Популярний кросовер у багатій комплектації, без ДТП.',
    priceUsd: 35500,
    mileageKm: 67000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'robot',
    driveTypeSlug: 'awd',
    colorSlug: 'white',
    engineVolumeL: '2.0',
    powerHp: 249,
    city: 'Одеса',
    optionSlugs: ['leather', 'panoramic-roof', 'parking-sensors', 'apple-carplay'],
  },
  {
    slug: 'mercedes-benz-c-class-2019-demo-12',
    makeSlug: 'mercedes-benz',
    modelSlug: 'c-class',
    year: 2019,
    title: 'Mercedes-Benz C 200 4MATIC 2019',
    description: 'Компактний бізнес-седан, м’яка гібридна система EQ Boost.',
    priceUsd: 28900,
    mileageKm: 71000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'silver',
    engineVolumeL: '1.5',
    powerHp: 184,
    city: 'Київ',
    optionSlugs: ['climate', 'cruise', 'led-headlights'],
  },
  {
    slug: 'mercedes-benz-c-class-2020-demo-13',
    makeSlug: 'mercedes-benz',
    modelSlug: 'c-class',
    year: 2020,
    title: 'Mercedes-Benz C 220d 2020',
    description: 'Дизель, AMG-пакет, підвіска Airmatic, сервісна історія Mercedes.',
    priceUsd: 33500,
    mileageKm: 58000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'diesel',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'rwd',
    colorSlug: 'black',
    engineVolumeL: '2.0',
    powerHp: 194,
    city: 'Львів',
    optionSlugs: ['leather', 'heated-seats', 'camera-360', 'apple-carplay'],
  },
  {
    slug: 'mercedes-benz-e-class-2019-demo-14',
    makeSlug: 'mercedes-benz',
    modelSlug: 'e-class',
    year: 2019,
    title: 'Mercedes-Benz E 220d 4MATIC 2019',
    description: 'Легендарний W213, повний привід, широкоформатні дисплеї.',
    priceUsd: 36900,
    mileageKm: 84000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'diesel',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'grey',
    engineVolumeL: '2.0',
    powerHp: 194,
    city: 'Київ',
    optionSlugs: ['leather', 'cruise', 'parking-sensors', 'heated-seats'],
  },
  {
    slug: 'mercedes-benz-e-class-2021-demo-15',
    makeSlug: 'mercedes-benz',
    modelSlug: 'e-class',
    year: 2021,
    title: 'Mercedes-Benz E 300 AMG Line 2021',
    description: 'Рестайлінг, MBUX, кермо з сенсорними панелями, стан ідеальний.',
    priceUsd: 47500,
    mileageKm: 41000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'rwd',
    colorSlug: 'blue',
    engineVolumeL: '2.0',
    powerHp: 258,
    city: 'Дніпро',
    optionSlugs: ['leather', 'panoramic-roof', 'camera-360', 'led-headlights'],
  },
  {
    slug: 'mercedes-benz-glc-2020-demo-16',
    makeSlug: 'mercedes-benz',
    modelSlug: 'glc',
    year: 2020,
    title: 'Mercedes-Benz GLC 300 4MATIC 2020',
    description: 'Рестайлінговий кросовер, безключовий доступ, електропривід багажника.',
    priceUsd: 41900,
    mileageKm: 62000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'white',
    engineVolumeL: '2.0',
    powerHp: 258,
    city: 'Київ',
    optionSlugs: ['leather', 'panoramic-roof', 'heated-seats', 'android-auto'],
  },
  {
    slug: 'volkswagen-passat-2019-demo-17',
    makeSlug: 'volkswagen',
    modelSlug: 'passat',
    year: 2019,
    title: 'Volkswagen Passat 2.0 TDI 2019',
    description: 'Надійний сімейний седан, недорогий в обслуговуванні, один власник.',
    priceUsd: 19900,
    mileageKm: 112000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'diesel',
    transmissionSlug: 'robot',
    driveTypeSlug: 'fwd',
    colorSlug: 'silver',
    engineVolumeL: '2.0',
    powerHp: 150,
    city: 'Вінниця',
    optionSlugs: ['climate', 'cruise', 'parking-sensors'],
  },
  {
    slug: 'volkswagen-passat-2021-demo-18',
    makeSlug: 'volkswagen',
    modelSlug: 'passat',
    year: 2021,
    title: 'Volkswagen Passat Elegance 2.0 TSI 2021',
    description: 'Топова комплектація Elegance, адаптивний круїз, LED Matrix.',
    priceUsd: 25900,
    mileageKm: 54000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'robot',
    driveTypeSlug: 'fwd',
    colorSlug: 'black',
    engineVolumeL: '2.0',
    powerHp: 190,
    city: 'Київ',
    optionSlugs: ['leather', 'led-headlights', 'apple-carplay', 'heated-seats'],
  },
  {
    slug: 'volkswagen-tiguan-2019-demo-19',
    makeSlug: 'volkswagen',
    modelSlug: 'tiguan',
    year: 2019,
    title: 'Volkswagen Tiguan 2.0 TSI 4Motion 2019',
    description: 'Повнопривідний кросовер, панорамний дах, зимовий пакет.',
    priceUsd: 23500,
    mileageKm: 96000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'robot',
    driveTypeSlug: 'awd',
    colorSlug: 'grey',
    engineVolumeL: '2.0',
    powerHp: 180,
    city: 'Львів',
    optionSlugs: ['panoramic-roof', 'heated-seats', 'parking-sensors'],
  },
  {
    slug: 'volkswagen-tiguan-2021-demo-20',
    makeSlug: 'volkswagen',
    modelSlug: 'tiguan',
    year: 2021,
    title: 'Volkswagen Tiguan R-Line 2021',
    description: 'Рестайлінг у пакеті R-Line, цифрова панель, стан нового.',
    priceUsd: 29900,
    mileageKm: 47000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'robot',
    driveTypeSlug: 'awd',
    colorSlug: 'white',
    engineVolumeL: '2.0',
    powerHp: 220,
    city: 'Київ',
    optionSlugs: ['leather', 'camera-360', 'led-headlights', 'android-auto'],
  },
  {
    slug: 'toyota-camry-2020-demo-21',
    makeSlug: 'toyota',
    modelSlug: 'camry',
    year: 2020,
    title: 'Toyota Camry 2.5 Hybrid 2020',
    description: 'Гібрид з мінімальною витратою, ідеальний для міста й таксі-класу люкс.',
    priceUsd: 27900,
    mileageKm: 69000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'hybrid',
    transmissionSlug: 'cvt',
    driveTypeSlug: 'fwd',
    colorSlug: 'black',
    engineVolumeL: '2.5',
    powerHp: 218,
    city: 'Одеса',
    optionSlugs: ['climate', 'cruise', 'heated-seats', 'apple-carplay'],
  },
  {
    slug: 'toyota-camry-2022-demo-22',
    makeSlug: 'toyota',
    modelSlug: 'camry',
    year: 2022,
    title: 'Toyota Camry 3.5 V6 2022',
    description: 'Рідкісний атмосферний V6, максимальна комплектація, гарантія.',
    priceUsd: 33900,
    mileageKm: 28000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'petrol',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'fwd',
    colorSlug: 'red',
    engineVolumeL: '3.5',
    powerHp: 301,
    city: 'Київ',
    optionSlugs: ['leather', 'led-headlights', 'camera-360', 'heated-seats'],
  },
  {
    slug: 'toyota-rav4-2021-demo-23',
    makeSlug: 'toyota',
    modelSlug: 'rav4',
    year: 2021,
    title: 'Toyota RAV4 2.5 Hybrid AWD 2021',
    description: 'Найпопулярніший гібридний кросовер, повний привід e-Four.',
    priceUsd: 31500,
    mileageKm: 52000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'hybrid',
    transmissionSlug: 'cvt',
    driveTypeSlug: 'awd',
    colorSlug: 'blue',
    engineVolumeL: '2.5',
    powerHp: 222,
    city: 'Харків',
    optionSlugs: ['climate', 'cruise', 'parking-sensors', 'android-auto'],
  },
  {
    slug: 'tesla-model-3-2021-demo-24',
    makeSlug: 'tesla',
    modelSlug: 'model-3',
    year: 2021,
    title: 'Tesla Model 3 Long Range 2021',
    description: 'Дальнобійна версія Dual Motor, автопілот, батарея у відмінному стані.',
    priceUsd: 30900,
    mileageKm: 44000,
    bodyTypeSlug: 'sedan',
    fuelTypeSlug: 'electric',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'white',
    engineVolumeL: '0.0',
    powerHp: 440,
    city: 'Київ',
    optionSlugs: ['panoramic-roof', 'camera-360', 'heated-seats'],
  },
  {
    slug: 'tesla-model-y-2022-demo-25',
    makeSlug: 'tesla',
    modelSlug: 'model-y',
    year: 2022,
    title: 'Tesla Model Y Long Range 2022',
    description: 'Просторий електрокросовер, запас ходу 500+ км, мінімальний пробіг.',
    priceUsd: 38900,
    mileageKm: 31000,
    bodyTypeSlug: 'suv',
    fuelTypeSlug: 'electric',
    transmissionSlug: 'automatic',
    driveTypeSlug: 'awd',
    colorSlug: 'black',
    engineVolumeL: '0.0',
    powerHp: 450,
    city: 'Львів',
    optionSlugs: ['panoramic-roof', 'camera-360', 'heated-seats', 'apple-carplay'],
  },
];
